#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
title: "Madison91905's ENGL350 Blog"
# Short bio or description (displayed in the header)
description: "Various entries updated throughout the course of fall 2020 for ENGL350: Writing for the Digital Humanities."

#
# !! DON'T EDIT BELOW THIS MESSAGE
#
# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
